INSERT INTO `country` VALUES (1, 'vn', 0);
-- ----------------------------
-- Records of country_translation
-- ----------------------------
INSERT INTO `country_translation` VALUES (1, 1, 'en', 'Vietnam');
INSERT INTO `country_translation` VALUES (2, 1, 'vi', 'Việt Nam');
-- ----------------------------
-- Records of city
-- ----------------------------
INSERT INTO `city` (id, country_id, `position`) VALUES (1, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (2, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (3, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (4, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (5, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (6, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (7, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (8, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (9, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (10, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (11, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (12, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (13, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (14, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (15, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (16, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (17, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (18, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (19, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (20, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (21, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (22, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (23, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (24, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (25, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (26, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (27, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (28, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES (29, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(30, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(31, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(32, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(33, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(34, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(35, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(36, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(37, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(38, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(39, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(40, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(41, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(42, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(43, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(44, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(45, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(46, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(47, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(48, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(49, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(50, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(51, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(52, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(53, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(54, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(55, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(56, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(57, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(58, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(59, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(60, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(61, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(62, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(63, 1, 0);
INSERT INTO `city` (id, country_id, `position`) VALUES(64, 1, 0);
-- ----------------------------
-- Records of city_translation
-- ----------------------------
INSERT INTO `city_translation` VALUES (1, 1, 'vi', 'Hà Nội');
INSERT INTO `city_translation` VALUES (2, 1, 'en', 'Ha Noi');
INSERT INTO `city_translation` VALUES (3, 2, 'vi', 'Hà Giang');
INSERT INTO `city_translation` VALUES (4, 2, 'en', 'Ha Giang');
INSERT INTO `city_translation` VALUES (5, 3, 'vi', 'Cao Bằng');
INSERT INTO `city_translation` VALUES (6, 3, 'en', 'Cao Bang');
INSERT INTO `city_translation` VALUES (7, 4, 'vi', 'Bắc Kạn');
INSERT INTO `city_translation` VALUES (8, 4, 'en', 'Bac Kan');
INSERT INTO `city_translation` VALUES (9, 5, 'vi', 'Tuyên Quang');
INSERT INTO `city_translation` VALUES (10, 5, 'en', 'Tuyen Quang');
INSERT INTO `city_translation` VALUES (11, 6, 'vi', 'Lào Cai');
INSERT INTO `city_translation` VALUES (12, 6, 'en', 'Lao Cai');
INSERT INTO `city_translation` VALUES (13, 7, 'vi', 'Điện Biên');
INSERT INTO `city_translation` VALUES (14, 7, 'en', 'Dien Bien');
INSERT INTO `city_translation` VALUES (15, 8, 'vi', 'Lai Châu');
INSERT INTO `city_translation` VALUES (16, 8, 'en', 'Lai Chau');
INSERT INTO `city_translation` VALUES (17, 9, 'vi', 'Sơn La');
INSERT INTO `city_translation` VALUES (18, 9, 'en', 'Son La');
INSERT INTO `city_translation` VALUES (19, 10, 'vi', 'Yên Bái');
INSERT INTO `city_translation` VALUES (20, 10, 'en', 'Yen Bai');
INSERT INTO `city_translation` VALUES (21, 11, 'vi', 'Hòa Bình');
INSERT INTO `city_translation` VALUES (22, 11, 'en', 'Hoa Binh');
INSERT INTO `city_translation` VALUES (23, 12, 'vi', 'Thái Nguyên');
INSERT INTO `city_translation` VALUES (24, 12, 'en', 'Thai Nguyen');
INSERT INTO `city_translation` VALUES (25, 13, 'vi', 'Lạng Sơn');
INSERT INTO `city_translation` VALUES (26, 13, 'en', 'Lang Son');
INSERT INTO `city_translation` VALUES (27, 14, 'vi', 'Quảng Ninh');
INSERT INTO `city_translation` VALUES (28, 14, 'en', 'Quang Ninh');
INSERT INTO `city_translation` VALUES (29, 15, 'vi', 'Bắc Giang');
INSERT INTO `city_translation` VALUES (30, 15, 'en', 'Bac Giang');
INSERT INTO `city_translation` VALUES (31, 16, 'vi', 'Phú Thọ');
INSERT INTO `city_translation` VALUES (32, 16, 'en', 'Phu Tho');
INSERT INTO `city_translation` VALUES (33, 17, 'vi', 'Vĩnh Phúc');
INSERT INTO `city_translation` VALUES (34, 17, 'en', 'Vinh Phuc');
INSERT INTO `city_translation` VALUES (35, 18, 'vi', 'Bắc Ninh');
INSERT INTO `city_translation` VALUES (36, 18, 'en', 'Bac Ninh');
INSERT INTO `city_translation` VALUES (37, 19, 'vi', 'Hải Dương');
INSERT INTO `city_translation` VALUES (38, 19, 'en', 'Hai Duong');
INSERT INTO `city_translation` VALUES (39, 20, 'vi', 'Hải Phòng');
INSERT INTO `city_translation` VALUES (40, 20, 'en', 'Hai Phong');
INSERT INTO `city_translation` VALUES (41, 21, 'vi', 'Hưng Yên');
INSERT INTO `city_translation` VALUES (42, 21, 'en', 'Hung Yen');
INSERT INTO `city_translation` VALUES (43, 22, 'vi', 'Thái Bình');
INSERT INTO `city_translation` VALUES (44, 22, 'en', 'Thai Binh');
INSERT INTO `city_translation` VALUES (45, 23, 'vi', 'Hà Nam');
INSERT INTO `city_translation` VALUES (46, 23, 'en', 'Ha Nam');
INSERT INTO `city_translation` VALUES (47, 24, 'vi', 'Nam Định');
INSERT INTO `city_translation` VALUES (48, 24, 'en', 'Nam Dinh');
INSERT INTO `city_translation` VALUES (49, 25, 'vi', 'Ninh Bình');
INSERT INTO `city_translation` VALUES (50, 25, 'en', 'Ninh Binh');
INSERT INTO `city_translation` VALUES (51, 26, 'vi', 'Thanh Hóa');
INSERT INTO `city_translation` VALUES (52, 26, 'en', 'Thanh Hoa');
INSERT INTO `city_translation` VALUES (53, 27, 'vi', 'Nghệ An');
INSERT INTO `city_translation` VALUES (54, 27, 'en', 'Nghe An');
INSERT INTO `city_translation` VALUES (55, 28, 'vi', 'Hà Tĩnh');
INSERT INTO `city_translation` VALUES (56, 28, 'en', 'Ha Tinh');
INSERT INTO `city_translation` VALUES (57, 29, 'vi', 'Quảng Bình');
INSERT INTO `city_translation` VALUES (58, 29, 'en', 'Quang Binh');
INSERT INTO `city_translation` VALUES (59, 30, 'vi', 'Quảng Trị');
INSERT INTO `city_translation` VALUES (60, 30, 'en', 'Quang Tri');
INSERT INTO `city_translation` VALUES (61, 31, 'vi', 'Thừa Thiên Huế');
INSERT INTO `city_translation` VALUES (62, 31, 'en', 'Thua Thien Hue');
INSERT INTO `city_translation` VALUES (63, 32, 'vi', 'Đà Nẵng');
INSERT INTO `city_translation` VALUES (64, 32, 'en', 'Da Nang');
INSERT INTO `city_translation` VALUES (65, 33, 'vi', 'Quảng Nam');
INSERT INTO `city_translation` VALUES (66, 33, 'en', 'Quang Nam');
INSERT INTO `city_translation` VALUES (67, 34, 'vi', 'Quảng Ngãi');
INSERT INTO `city_translation` VALUES (68, 34, 'en', 'Quang Ngai');
INSERT INTO `city_translation` VALUES (69, 35, 'vi', 'Bình Định');
INSERT INTO `city_translation` VALUES (70, 35, 'en', 'Binh Dinh');
INSERT INTO `city_translation` VALUES (71, 36, 'vi', 'Phú Yên');
INSERT INTO `city_translation` VALUES (72, 36, 'en', 'Phu Yen');
INSERT INTO `city_translation` VALUES (73, 37, 'vi', 'Khánh Hòa');
INSERT INTO `city_translation` VALUES (74, 37, 'en', 'Khanh Hoa');
INSERT INTO `city_translation` VALUES (75, 38, 'vi', 'Ninh Thuận');
INSERT INTO `city_translation` VALUES (76, 38, 'en', 'Ninh Thuan');
INSERT INTO `city_translation` VALUES (77, 39, 'vi', 'Bình Thuận');
INSERT INTO `city_translation` VALUES (78, 39, 'en', 'Binh Thuan');
INSERT INTO `city_translation` VALUES (79, 40, 'vi', 'Kon Tum');
INSERT INTO `city_translation` VALUES (80, 40, 'en', 'Kon Tum');
INSERT INTO `city_translation` VALUES (81, 41, 'vi', 'Gia Lai');
INSERT INTO `city_translation` VALUES (82, 41, 'en', 'Gia Lai');
INSERT INTO `city_translation` VALUES (83, 42, 'vi', 'Đắk Lắk');
INSERT INTO `city_translation` VALUES (84, 42, 'en', 'Dak Lak');
INSERT INTO `city_translation` VALUES (85, 43, 'vi', 'Đắk Nông');
INSERT INTO `city_translation` VALUES (86, 43, 'en', 'Dak Nong');
INSERT INTO `city_translation` VALUES (87, 44, 'vi', 'Lâm Đồng');
INSERT INTO `city_translation` VALUES (88, 44, 'en', 'Lam Dong');
INSERT INTO `city_translation` VALUES (89, 45, 'vi', 'Bình Phước');
INSERT INTO `city_translation` VALUES (90, 45, 'en', 'Binh Phuoc');
INSERT INTO `city_translation` VALUES (91, 46, 'vi', 'Tây Ninh');
INSERT INTO `city_translation` VALUES (92, 46, 'en', 'Tay Ninh');
INSERT INTO `city_translation` VALUES (93, 47, 'vi', 'Bình Dương');
INSERT INTO `city_translation` VALUES (94, 47, 'en', 'Binh Duong');
INSERT INTO `city_translation` VALUES (95, 48, 'vi', 'Đồng Nai');
INSERT INTO `city_translation` VALUES (96, 48, 'en', 'Dong Nai');
INSERT INTO `city_translation` VALUES (97, 49, 'vi', 'Bà Rịa - Vũng Tàu');
INSERT INTO `city_translation` VALUES (98, 49, 'en', 'Ba Ria - Vung Tau');
INSERT INTO `city_translation` VALUES (99, 50, 'vi', 'Hồ Chí Minh');
INSERT INTO `city_translation` VALUES (100, 50, 'en', 'Ho Chi Minh');
INSERT INTO `city_translation` VALUES (101, 51, 'vi', 'Long An');
INSERT INTO `city_translation` VALUES (102, 51, 'en', 'Long An');
INSERT INTO `city_translation` VALUES (103, 52, 'vi', 'Tiền Giang');
INSERT INTO `city_translation` VALUES (104, 52, 'en', 'Tien Giang');
INSERT INTO `city_translation` VALUES (105, 53, 'vi', 'Bến Tre');
INSERT INTO `city_translation` VALUES (106, 53, 'en', 'Ben Tre');
INSERT INTO `city_translation` VALUES (107, 54, 'vi', 'Trà Vinh');
INSERT INTO `city_translation` VALUES (108, 54, 'en', 'Tra Vinh');
INSERT INTO `city_translation` VALUES (109, 55, 'vi', 'Vĩnh Long');
INSERT INTO `city_translation` VALUES (110, 55, 'en', 'Vinh Long');
INSERT INTO `city_translation` VALUES (111, 56, 'vi', 'Đồng Tháp');
INSERT INTO `city_translation` VALUES (112, 56, 'en', 'Dong Thap');
INSERT INTO `city_translation` VALUES (113, 57, 'vi', 'An Giang');
INSERT INTO `city_translation` VALUES (114, 57, 'en', 'An Giang');
INSERT INTO `city_translation` VALUES (115, 58, 'vi', 'Kiên Giang');
INSERT INTO `city_translation` VALUES (116, 58, 'en', 'Kien Giang');
INSERT INTO `city_translation` VALUES (117, 59, 'vi', 'Cần Thơ');
INSERT INTO `city_translation` VALUES (118, 59, 'en', 'Can Tho');
INSERT INTO `city_translation` VALUES (119, 60, 'vi', 'Hậu Giang');
INSERT INTO `city_translation` VALUES (120, 60, 'en', 'Hau Giang');
INSERT INTO `city_translation` VALUES (121, 61, 'vi', 'Sóc Trăng');
INSERT INTO `city_translation` VALUES (122, 61, 'en', 'Soc Trang');
INSERT INTO `city_translation` VALUES (123, 62, 'vi', 'Bạc Liêu');
INSERT INTO `city_translation` VALUES (124, 62, 'en', 'Bac Lieu');
INSERT INTO `city_translation` VALUES (125, 63, 'vi', 'Cà Mau');
INSERT INTO `city_translation` VALUES (126, 63, 'en', 'Ca Mau');
INSERT INTO `city_translation` VALUES (127, 64, 'vi', 'Nhà Phân Phối Nước Ngoài');
INSERT INTO `city_translation` VALUES (128, 64, 'en', 'Foreign Distributors');
